name: IssueCreationTriggerPipeline
on: 
  issues:
    types: [opened, edited, milestoned]
jobs:
  Issue_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ toJson(github.event) }} event."
